[package]
name = "libmapper-rs"
version = "1.0.0"
edition = "2021"
description = "Rust bindings for libmapper"
license = "Apache-2.0"
homepage = "https://libmapper.github.io"
repository = "https://github.com/libmapper/libmapper-rs"

[dependencies]

[build-dependencies]
pkg-config = "0.3.30"
